### PR TITLE
Add example for configuring Sphinx with Capistrano

### PR DESCRIPTION
**Pull request by gyozadoc**
Add example for configuring TS with Capistrano

Contributed by @bsodmike

### CODE REVIEW

**Comment by bsodmike** [comment]
Hey @pat hope this is OK? Thanks :)

**Comment by pat** [comment]
Thanks for the patch Mike, it's certainly appreciated, but I don't think what you've put together is necessary.

* If you have the paths set up like covered in the existing documentation, then you shouldn't need any symlinks at all.
* I don't recommend restarting Sphinx on every deploy, as it shouldn't be necessary. It really should just work smoothly, and then you'll want to run a rebuild or regenerate whenever your Sphinx indices change structure.
* Thinking Sphinx has Capistrano tasks built in already, so you don't need to define your own (unless, of course, the standard TS approach isn't quite what you're after).

You can find a test app with TS Capistrano integration here, which I've used to test the provided tasks work well: https://github.com/pat/captest

All that said, please note that I really do appreciate the effort you've put in to submitting this! And if you're submitting it, then that probably means the existing documentation isn't clear enough, so I'm keen to hear what parts of it don't make sense.

**Comment by bsodmike** [comment]
Hey thanks for the feedback @pat.

> I don't recommend restarting Sphinx on every deploy, as it shouldn't be necessary. It really should just work smoothly, and then you'll want to run a rebuild or regenerate whenever your Sphinx indices change structure.

Good point, I'll amend this in my build.  Further to this, I will also remove the re-indexing on each deploy, and move this to run via a cron-job through Whenever.

> And if you're submitting it, then that probably means the existing documentation isn't clear enough, so I'm keen to hear what parts of it don't make sense.

Ta, I'll use the included tasks - just need to call them from the hooks as I want them to run as part of the deploy, rather than (as per your captest example) have to issue the TS rebuild.  So per deploy, I just want to make sure that (i) TS is configured and (ii) it's running.  However, most builds will most likely have (ii) being monitored by say Upstart/Monit etc.

Thanks again, feel free to close this :)

**Comment by pat** [comment]
If you've got the configuration file being set up in a shared directory (instead of a release directory), then you shouldn't even need to worry about (i) either? It'll be in a reliable location that way.

**Comment by bsodmike** [comment]
Yeah, I'm yanking out the symlink - that's not needed.  Also didn't see this hiding here,
https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/capistrano/v3.rb#L79

Ha!

**Comment by pat** [comment]
Great :)

**Pull request closed without merging**
